- title: Договор купли-продажи транспортного средства
  template_text: |
    {title}
    {date}. {city}
    
    {personal_data_buyer}
    
    {personal_data_seller}
    
    {subject_of_contract}
    
    {cost_and_payment_terms}
    
    {guarantees_and_liability}
    
    {final_provisions}
    
    {signatures}
  fields:
    - date
    - city
    - buyer_name
    - buyer_surname
    - buyer_birthdate
    - buyer_address
    - buyer_pass_series
    - buyer_pass_number
    - buyer_pass_issued_by
    - buyer_pass_time
    - seller_name
    - seller_surname
    - seller_birthdate
    - seller_address
    - seller_pass_series
    - seller_pass_number
    - seller_pass_issued_by
    - seller_pass_time
    - vehicle_brand
    - vehicle_model
    - vehicle_vin
    - vehicle_type
    - vehicle_year
    - vehicle_mileage
    - vehicle_engine_power
    - vehicle_engine_volume
    - vehicle_body_color
    - vehicle_engine_model
    - vehicle_engine_number
    - vehicle_chassis_number
    - vehicle_body_number
    - vehicle_pass_series
    - vehicle_pass_number
    - vehicle_pass_issued_by
    - vehicle_pass_time
    - vehicle_license_plate
    - vehicle_price
  sections:
    - text: "Договор купли-продажи транспортного средства"
      font_size: 15
      font_style: B
      align: C
    - text: "{date}. г.{city}"
      font_size: 11
      font_style: ""
      align: L
    - text: "{buyer_name} {buyer_surname}, {buyer_birthdate}, {buyer_address}. Паспорт: серия {buyer_pass_series}, номер {buyer_pass_number}, выдан {buyer_pass_issued_by} {buyer_pass_time} именуемый(ая) в дальнейшем  «Покупатель» с одной стороны, и"
      font_size: 11
      font_style: ""
      align: L
    - text: "{seller_name} {seller_surname}, {seller_birthdate}, {seller_address}. Паспорт: серия {seller_pass_series}, номер {seller_pass_number}, выдан {seller_pass_issued_by} {seller_pass_time} именуемый(ая) в дальнейшем «Продавец» с другой стороны, и именуемые далее при совместном упоминании «Стороны», а по отдельности «Сторона», заключили настоящий договор (далее - «Договор») о нижеследующем:"
      font_size: 11
      font_style: ""
      align: L
    - title: Предмет договора
      text: |
        1.1 Продавец обязуется передать в собственность Покупателя, а Покупатель — принять и оплатить транспортное средство (далее — ТС).
        1.2 Собственником ТС до его передачи Покупателю является Продавец (свидетельство о регистрации транспортного средства серия {vehicle_pass_series}, номер {vehicle_pass_number}, выдано «{vehicle_pass_issued_by}» {vehicle_pass_time} г.).
        Право собственности на ТС переходит к Покупателю с момента подписания настоящего Договора.
      font_size: 11
      font_style: ""
      align: L
      title_font_size: 12
      title_font_style: B
    - title: Стоимость ТС и порядок расчетов
      text: |
        2.1 Стоимость ТС составляет {vehicle_price} рублей (НДС не облагается). Оплата стоимости ТС производится путем 100% предоплаты (наличным или безналичным расчетом).
      font_size: 11
      font_style: ""
      align: L
      title_font_size: 12
      title_font_style: B
    - title: Гарантии и ответственность
      text: |
        Продавец гарантирует Покупателю, что:
        Продавец является собственником ТС.
        ТС не является предметом обязательств Продавца перед третьими лицами, в том числе не является предметом залога, в отношении ТС не наложен запрет на совершение регистрационных действий, ТС не находится под арестом, не числится в базах данных МВД России как угнанное или похищенное транспортное средство и не имеет иных обременений.
        В случае нарушения гарантий, указанных выше, Продавец обязуется незамедлительно возвратить Покупателю стоимость ТС в полном объеме со дня обнаружения соответствующего нарушения.
      font_size: 11
      font_style: ""
      align: L
      title_font_size: 12
      title_font_style: B
    - title: Заключительные положения
      text: |
        Настоящий Договор вступает в силу после его подписания Сторонами и действует до момента полного исполнения Сторонами своих обязательств по Договору. Договор составлен в трех экземплярах, имеющих равную юридическую силу.
      font_size: 11
      font_style: ""
      align: L
      title_font_size: 12
      title_font_style: B
    - text: |
        Продавец: ________________________ Расшифровка: ________________________
        Покупатель: ________________________ Расшифровка: ________________________
      font_size: 11
      font_style: ""
      align: L

- title: Договор аренды квартиры
  template_text: |
    {title}
    {date}. {city}
    
    {landlord_info}
    
    {tenant_info}
    
    {rental_property_details}
    
    {payment_terms}
    
    {rights_and_obligations}
    
    {liability_and_disputes}
    
    {termination_conditions}
    
    {signatures}
  fields:
    - date
    - city
    - landlord_name
    - landlord_company
    - landlord_representative
    - landlord_basis
    - tenant_name
    - tenant_pass_series
    - tenant_pass_number
    - tenant_pass_issued_by
    - tenant_address
    - property_address
    - property_area
    - property_condition
    - rental_purpose
    - rent_amount
    - rent_due_date
    - utility_expenses
    - deposit_amount
    - contract_duration
    - termination_notice_period
  sections:
    - text: "Договор аренды квартиры"
      font_size: 15
      font_style: B
      align: C
    - text: "{date}. г.{city}"
      font_size: 11
      font_style: ""
      align: L
    - text: "{landlord_name}, {landlord_company}, в лице {landlord_representative}, действующего на основании {landlord_basis}, именуемый в дальнейшем 'Арендодатель', с одной стороны, и"
      font_size: 11
      font_style: ""
      align: L
    - text: "{tenant_name}, паспорт: серия {tenant_pass_series}, номер {tenant_pass_number}, выдан {tenant_pass_issued_by}, зарегистрированный по адресу {tenant_address}, именуемый в дальнейшем 'Арендатор', с другой стороны, совместно именуемые 'Стороны', заключили настоящий договор о нижеследующем:"
      font_size: 11
      font_style: ""
      align: L
    - title: Предмет договора
      text: |
        1.1. Арендодатель предоставляет Арендатору в аренду жилое помещение по адресу: {property_address}, площадью {property_area} кв.м.
        1.2. Состояние помещения: {property_condition}.
        1.3. Цель аренды: {rental_purpose}.
      font_size: 11
      font_style: ""
      align: L
      title_font_size: 12
      title_font_style: B
    - title: Арендные платежи и порядок расчетов
      text: |
        2.1. Размер арендной платы: {rent_amount} рублей в месяц.
        2.2. Дата оплаты: {rent_due_date}.
        2.3. Коммунальные платежи: {utility_expenses}.
        2.4. Залог: {deposit_amount} рублей.
      font_size: 11
      font_style: ""
      align: L
      title_font_size: 12
      title_font_style: B
    - title: Права и обязанности сторон
      text: |
        3.1. Арендодатель обязуется предоставить жилое помещение в исправном состоянии.
        3.2. Арендатор обязан использовать помещение строго в соответствии с его назначением и содержать его в надлежащем состоянии.
      font_size: 11
      font_style: ""
      align: L
      title_font_size: 12
      title_font_style: B
    - title: Ответственность и урегулирование споров
      text: |
        4.1. Стороны несут ответственность за нарушение условий договора в соответствии с законодательством РФ.
        4.2. Все споры решаются путем переговоров или в судебном порядке.
      font_size: 11
      font_style: ""
      align: L
      title_font_size: 12
      title_font_style: B
    - title: Расторжение договора
      text: |
        5.1. Договор действует в течение {contract_duration}.
        5.2. Для расторжения договора необходимо уведомить другую сторону за {termination_notice_period}.
      font_size: 11
      font_style: ""
      align: L
      title_font_size: 12
      title_font_style: B
    - text: |
        Арендодатель: ________________________ Расшифровка: ________________________
        Арендатор: ________________________ Расшифровка: ________________________
      font_size: 11
      font_style: ""
      align: L