ru:
  start: "Привет! Я бот для работы с документами. Выберите действие:"
  help: "Доступные команды:\n/start - Начать работу с ботом\n/help - Показать эту справку\n/select_doc - Выбрать документ\n/input_data - Ввести данные для документа\n/generate_doc - Сгенерировать выбранный документ"
  input_data: "Введите данные для документа через запятую:\n"
  input_data_error: "Сначала выберите документ."
  input_data_format_error: "Неправильный формат ввода. Ожидается {count} полей."
  input_data_repeat: "Пожалуйста, введите данные заново."
  input_data_success: "Данные приняты. Теперь вы можете сгенерировать документ."
  select_doc: "Выберите документ:\n"
  select_doc_error: "Нет документов для выбора."
  select_doc_number_error: "Неправильный номер документа."
  select_doc_success: "Документ выбран. Теперь вы можете ввести данные."
  generate_doc_error: "Сначала выберите документ."
  generate_doc_data_error: "Сначала введите данные для документа."
  generate_doc_error_message: "Ошибка при генерации документа."
  button_commands: "Команды"
  button_select_doc: "Выбрать документ"
  button_generate_doc: "Сгенерировать документ"

en:
  start: "Hello! I'm a bot for working with documents. Choose an action:"
  help: "Available commands:\n/start - Start working with the bot\n/help - Show this help\n/select_doc - Select a document\n/input_data - Enter data for the document\n/generate_doc - Generate the selected document"
  input_data: "Enter data for the document through commas:\n"
  input_data_error: "First, select a document."
  input_data_format_error: "Incorrect input format. Expecting {count} fields."
  input_data_repeat: "Please enter the data again."
  input_data_success: "Data accepted. Now you can generate the document."
  select_doc: "Select a document:\n"
  select_doc_error: "No documents available for selection."
  select_doc_number_error: "Incorrect document number."
  select_doc_success: "Document selected. Now you can enter data."
  generate_doc_error: "First, select a document."
  generate_doc_data_error: "First, enter data for the document."
  generate_doc_error_message: "Error generating the document."
  button_commands: "Commands"
  button_select_doc: "Select Document"
  button_generate_doc: "Generate Document"
